### ISSUE TITLE
License？

### ISSUE THREAD

**Issue by toyo-cat** [ClaudeMarais/GPS_Tracking_Cat_Collar_XIAO_ESP32-C3#1]
I like the simple structure!
I would like to use it too, but I can't find a license.
I'm a beginner and would like to add some features.
It would be nice to have a license so I can use it with peace of mind.
Can you add it?

**Comment by ClaudeMarais** [comment]
Thanks for the comment, I just added the license.

**Comment by toyo-cat** [comment]
Thank you! 
I'm very happy.
